//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Description { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
